### ISSUE TITLE
CTF Platform

### ISSUE THREAD

**Issue by suyash-chavan** [Walchand-Linux-Users-Group/wcewlug.org#3]
We can create a CTF Platform for upcoming CTFs by using [CTFd Platform](https://github.com/CTFd/CTFd). Further machines/interactive challenges can be deployed on Heroku/Digital Ocean.

**Comment by wcewlug** [comment]
**UPDATED** in the plan.

**Comment by akhilesh1232** [comment]
Digital ocean droplets are paid we can deploy interactive challenges on Heroku.

**Comment by wcewlug** [comment]
CTFd 3.3.0 latest release is cloned. Hope you will configure it on Server.
